CREATE TABLE IF NOT EXISTS challenges (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name VARCHAR(64) NOT NULL,
	description TEXT,
	duration_ms INTEGER NOT NULL,
	seed_type TEXT CHECK (seed_type IN ('fixed', 'random')) NOT NULL,
	difficulty INTEGER NOT NULL DEFAULT 1, 
	active BOOLEAN DEFAULT TRUE,
	config_json TEXT NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
