-- Seed Rocket League ranks with tier, tier_number, and division
INSERT INTO ranks (tier, tier_number, division) VALUES
('Bronze', 1, 1),
('Bronze', 1, 2),
('Bronze', 1, 3),
('Bronze', 1, 4),
('Bronze', 2, 1),
('Bronze', 2, 2),
('Bronze', 2, 3),
('Bronze', 2, 4),
('Bronze', 3, 1),
('Bronze', 3, 2),
('Bronze', 3, 3),
('Bronze', 3, 4),
('Silver', 1, 1),
('Silver', 1, 2),
('Silver', 1, 3),
('Silver', 1, 4),
('Silver', 2, 1),
('Silver', 2, 2),
('Silver', 2, 3),
('Silver', 2, 4),
('Silver', 3, 1),
('Silver', 3, 2),
('Silver', 3, 3),
('Silver', 3, 4),
('Gold', 1, 1),
('Gold', 1, 2),
('Gold', 1, 3),
('Gold', 1, 4),
('Gold', 2, 1),
('Gold', 2, 2),
('Gold', 2, 3),
('Gold', 2, 4),
('Gold', 3, 1),
('Gold', 3, 2),
('Gold', 3, 3),
('Gold', 3, 4),
('Platinum', 1, 1),
('Platinum', 1, 2),
('Platinum', 1, 3),
('Platinum', 1, 4),
('Platinum', 2, 1),
('Platinum', 2, 2),
('Platinum', 2, 3),
('Platinum', 2, 4),
('Platinum', 3, 1),
('Platinum', 3, 2),
('Platinum', 3, 3),
('Platinum', 3, 4),
('Diamond', 1, 1),
('Diamond', 1, 2),
('Diamond', 1, 3),
('Diamond', 1, 4),
('Diamond', 2, 1),
('Diamond', 2, 2),
('Diamond', 2, 3),
('Diamond', 2, 4),
('Diamond', 3, 1),
('Diamond', 3, 2),
('Diamond', 3, 3),
('Diamond', 3, 4),
('Champion', 1, 1),
('Champion', 1, 2),
('Champion', 1, 3),
('Champion', 1, 4),
('Champion', 2, 1),
('Champion', 2, 2),
('Champion', 2, 3),
('Champion', 2, 4),
('Champion', 3, 1),
('Champion', 3, 2),
('Champion', 3, 3),
('Champion', 3, 4),
('Grand Champion', 1, 1),
('Grand Champion', 1, 2),
('Grand Champion', 1, 3),
('Grand Champion', 1, 4),
('Grand Champion', 2, 1),
('Grand Champion', 2, 2),
('Grand Champion', 2, 3),
('Grand Champion', 2, 4),
('Grand Champion', 3, 1),
('Grand Champion', 3, 2),
('Grand Champion', 3, 3),
('Grand Champion', 3, 4),
('Supersonic Legend', NULL, NULL);